pipeline {
    agent any
    
    stages {
        stage("SCM checkout (clone)") {
            steps {
                git "https://github.com/gazpacho-cloud/geocit-cloud-infrastructure.git"
            }
        }
        
        stage("Execute Ansible") {
            steps {
                ansiblePlaybook credentialsId: 'wushatneen',
                                 disableHostKeyChecking: true,
                                 installation: 'Ansible',
                                 inventory: 'inventory.ini',
                                 playbook: 'playbook.yml'
            }    
        }    
    }
}