pipeline {
    agent any
    tools {
        maven "M3"
		jfrog 'jfrog-cli'
	}
    parameters {
        choice(name: 'ENV', choices: ['DEV', 'STAGE', 'PROD'], description: 'Deployment environment')
    }
    environment {
        WORKING_DIR = "${WORKSPACE}/arifactory_build"
        NAME_ARTIFACT = sh(script: 'echo "citizen-${GIT_BRANCH}-${HASH_COMMIT}.war"', returnStdout: true)
        // NAME_ARTIFACT = "citizen-${GIT_BRANCH}-${HASH_COMMIT}.war"
        GOOGLE_CREDENTIALS = credentials('gcp-service-account')
    }
    stages {
    
        stage('git checkout') {
                steps {
                    script {
                        git branch: 'main', url: 'https://github.com/CapybaraDevOps/geocit.git'
                    }
                }
        }
        stage('Verify Workspace') {
                steps {
                    sh 'ls -al'
                    sh 'ls -al Jenkins'
    }
}


        stage('add credentials') {
            steps {
                script {
                    dir("${WORKING_DIR }/src/main/resources/") {
                        withCredentials([
                        file(
                            credentialsId: 'gcp-service-account',
                            variable: 'test')
                        ]) {
                            sh 'cp "\$test" application.properties'
                            sh "bash .Jenkins/env.sh"
                            sh "echo ${NAME_ARTIFACT}"
                        }
                    }
                }
            }
        }
        stage('Build Back-end') {
            steps {
                sh "mvn clean package -Dmaven.test.skip=true"
            }
        }
        stage('Test Back-end') {
            steps {
                sh "mvn test"
            }
        }
        stage('Artifactory') {
            steps {
                script {
                    def hash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def buildName = "${params.ENV}-${params.BUILDNAME}-$BUILD_NUMBER-${hash}"

                    def repo = ""
                    if (params.ENV == 'DEV') {
                        repo = 'dev-maven-local'
                    } else if (params.ENV == 'STAGE') {
                        repo = 'stage-maven-local'
                    } else if (params.ENV == 'PROD') {
                        repo = 'prod-maven-local'
                    }

                    jf "rt u /var/lib/jenkins/workspace/${WORKING_DIR}/target/citizen.war ${repo}/${NAME_ARTIFACT}.war"
                    jf "rt bp"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}