pipeline {
    agent any
    tools {
        maven "M3"
		jfrog 'jfrog-cli'
	}
    parameters {
        choice(name: 'ENV', choices: ['DEV', 'STAGE', 'PROD'], description: 'Deployment environment')
    }
    environment {
        NAME_ARTIFACT = sh(script: 'echo "citizen-${GIT_BRANCH}-${HASH_COMMIT}.war"', returnStdout: true)
        GOOGLE_CREDENTIALS = credentials('gcp-service-account')
    }
    stages {
    
        stage('git checkout') {
                steps {
                    script {
                        git branch: 'main', url: 'https://github.com/gazpacho-cloud/geocit.git'
                    }
                }
        }
        stage('Build Back-end') {
            steps {
                sh "mvn clean package -Dmaven.test.skip=true"
            }
        }
        stage('Test Back-end') {
            steps {
                sh "mvn test"
            }
        }
        stage('Artifactory') {
            steps {
                script {
                    def hash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def buildName = "${params.ENV}-citizen-$BUILD_NUMBER-${hash}.war"

                    def repo = ""
                    if (params.ENV == 'DEV') {
                        repo = 'dev-maven-local'
                    } else if (params.ENV == 'STAGE') {
                        repo = 'stage-maven-local'
                    } else if (params.ENV == 'PROD') {
                        repo = 'prod-maven-local'
                    }                
                    jf "rt u ${WORKSPACE}/target/citizen.war ${repo}/${buildName}"
                    jf "rt bp"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}