/* groovylint-disable CompileStatic, DuplicateStringLiteral, LineLength */
pipeline {
    agent any
    environment {
        ANSIBLE_VAULT_PASSWORD_FILE = credentials('ANSIBLE_VAULT_PASSWORD')
        GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp-service-account')
        WORKING_DIR = "./ansible"
    }
    stages {
        stage('Ansible') {
            steps {
                echo 'Ansible'
                dir(".") {
                        sh "ansible-playbook -i inventory.ini -l node_exporters  --vault-password-file ${ANSIBLE_VAULT_PASSWORD_FILE} playbook.yml"
                        }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}